name: Update Project Version
description: Update project and reference project version.
inputs:
  github-token:
    description: GitHub token
    required: true
  target-dir:
    description: Target Directory
    required: true
runs:
  using: composite
  steps:
  - name: Chackout Code
    uses: actions/checkout@v2
    with: 
      repository: Hedgehogs0808/UpdateCsprojectVersion
      path: ./UpdateProjectVersion

  - name: ls
    shell: bash
    run: ls -R

  - name: Check Release View
    shell: pwsh
    run: "./UpdateProjectVersion/scripts/update_version.ps1"

branding:
  icon: arrow-up
  color: green
