name: Update Project Version
description: Update project and reference project version.
inputs:
  github-token:
    description: GitHub token
    required: true
  target-dir:
    description: Target Directory
    required: true
runs:
  using: composite
  steps:
  - name: Chackout Code
    uses: actions/checkout@v2

  - name: ls
    shell: bash
    run: ls -al

  - name: Check Release View
    shell: pwsh
    run: ./scripts/update_version.ps1
branding:
  icon: arrow-up
  color: green
