name: Update Project Version
description: Update project and reference project version
inputs:
  targetDir:
    description: Target Directory
    required: true
  githubToken:
    description: GitHub token
    required: false
    default: ""
  isCommit:
    description: Commit the updated version of the project
    type: boolean
    required: false
    default: false
  addTag:
    description: Add tag by updated version
    type: boolean
    required: false
    default: false
runs:
  using: "composite"
  steps:
  - name: Chackout Code
    uses: actions/checkout@v3
    with: 
      repository: Hedgehogs0808/UpdateCsprojectVersion
      path: ./UpdateProjectVersion

  - name: Update Project Version
    shell: pwsh
    run: ./UpdateProjectVersion/scripts/update_version.ps1 -src_dir ${{ inputs.targetDir }}

  - name: Commit Update Files
    if: ${{ inputs.isCommit }}
    shell: pwsh
    run: |
      git config core.filemode false
      git add --update
      git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
      git config --local user.name "github-actions[bot]"
      git commit -m "Commit updated files"
      git push

  - name: Add Tag
    if: ( ${{ inputs.isCommit }} & ${{ inputs.addTag}} )
    shell: pwsh
    run: |
      git tag -a $newver -m $newver
      git push origin $newver

branding:
  icon: arrow-up
  color: green
